version: '3'
services:
  back-office-staging:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    ports:
      - ${PORT}:3000
    environment:
      - NODE_ENV=production
    command: yarn start
