# Utilisez une image de base contenant Node.js
FROM node:18-alpine

# Installe Python, make et g++ pour les dépendances natives
RUN apk add --no-cache python3 make g++

# Installez Angular CLI globalement
RUN npm install -g @angular/cli

# Définissez le répertoire de travail
WORKDIR /app

# Copiez les fichiers de package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Copiez le reste des fichiers de l'application
COPY . .

# Exposez le port utilisé par le serveur de développement Angular (4200 par défaut)
EXPOSE 4200

# Démarrez le serveur de développement Angular
CMD ["ng", "serve", "--host", "0.0.0.0"]